@HostAddress = http://localhost:5245

### 1. Добавить нового пользователя (Заказчика)
POST {{HostAddress}}/api/users
Content-Type: application/json

{
  "name": "Arina",
  "email": "arina@test.com",
  "passwordHash": "my_secret_password",
  "role": "Customer"
}

### 

### 2. Получить список всех пользователей
GET {{HostAddress}}/api/users
Accept: application/json