@HostAddress = http://localhost:5245

### 1. Додати нового користувача (Замовника)
POST {{HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "Аріна",
  "lastName": "Замовниця",
  "email": "arina@test.com",
  "password": "my_secret_password",
  "role": "Customer"
}

###

### 2. Отримати список всіх замовлень
GET {{HostAddress}}/api/orders
Accept: application/json

###

### 3. Створити новий заказ (від імені користувача id: 1)
POST {{HostAddress}}/api/orders
Content-Type: application/json

{
  "title": "Розробити дизайн лендингу",
  "description": "Потрібен сучасний дизайн для магазину у Figma",
  "budget": 500.00,
  "deadline": "2026-04-15T00:00:00Z",
  "status": "Open",
  "customerId": 1
}

### 4. Отримати список всіх замовлень
GET {{HostAddress}}/api/orders
Accept: application/json

###

### 5. Зареєструвати Фрілансера (отримає новий ID)
POST {{HostAddress}}/api/auth/register
Content-Type: application/json

{
  "name": "Максим",
  "lastName": "Фрілансер",
  "email": "max@freelance.com",
  "password": "secure_pass",
  "role": "Freelancer"
}

### 

### 6. Залишити відгук на замовлення
POST {{HostAddress}}/api/proposals
Content-Type: application/json

{
  "coverLetter": "Привіт! Я експерт у веб-дизайні, зроблю все швидко та красиво.",
  "price": 450.00,
  "deliveryDays": 5,
  "orderId": 1,
  "freelancerId": 2
}
